FROM eclipse-temurin:21-jdk AS build
WORKDIR /src
COPY mvnw mvnw
COPY .mvn .mvn
COPY pom.xml pom.xml
COPY inner-parent inner-parent
COPY tools tools
COPY domain domain
COPY application application
COPY adapter-persistence adapter-persistence
COPY adapter-web adapter-web
COPY bootstrap bootstrap
RUN ./mvnw -B -pl bootstrap -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /src/bootstrap/target/bootstrap-0.1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
